"""Slow integration test against real scanned guideline PDFs (206_2.pdf,
1003_1.pdf, repo root — manually provided fixtures, not regenerated by
any script). Requires the system `tesseract` binary with Russian language
data. Run explicitly:

    pytest tests/test_ocr_integration.py -v -m slow
"""
from pathlib import Path

import pytest

from RAG.ingestion.data_loader import PDFContentReader

_ROOT = Path(__file__).resolve().parent.parent


@pytest.mark.slow
@pytest.mark.parametrize("filename", ["206_2.pdf", "1003_1.pdf"])
def test_scanned_pdf_produces_text_chunks(filename):
    pdf_path = _ROOT / filename
    if not pdf_path.exists():
        pytest.skip(f"{filename} not present at repo root — manual fixture required")

    reader = PDFContentReader(pdf_path, metadata={"ID": "INTEGRATION_TEST"})
    chunks = list(reader.iter_chunks())
    text_chunks = [c for c in chunks if c["type"] == "text"]

    assert len(text_chunks) > 0, f"{filename}: OCR fallback produced zero text chunks"
    total_chars = sum(len(c["content"]) for c in text_chunks)
    assert total_chars > 500, f"{filename}: only {total_chars} chars extracted — OCR likely not firing"
