-- 002_docs.sql
-- Stores ingested PDF chunks with per-query-type hypothetical-query text and embeddings.
--
-- EMBEDDING_DIM must match the model used for embedding generation.
-- Default: 1024  (Qwen/Qwen3-Embedding-4B)
-- Change the dimension literals below if you switch embedding models.

CREATE TABLE IF NOT EXISTS docs (
    id              UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
    file_id         TEXT        NOT NULL,               -- manifest ID (PDF filename stem)
    chunk           TEXT        NOT NULL,               -- original extracted text / serialised table rows
    metadata        JSONB       NOT NULL DEFAULT '{}',  -- all fields from manifest.csv + page, section

    -- Hypothetical queries generated by the LLM (reverse HyDE)
    fact_q          TEXT,
    procedure_q     TEXT,
    constraint_q    TEXT,

    -- Per-query embeddings (dimension = 1024, adjust if needed)
    fact_q_embedding        VECTOR(1024),
    procedure_q_embedding   VECTOR(1024),
    constraint_q_embedding  VECTOR(1024)
);

-- HNSW indexes for fast approximate nearest-neighbour search using cosine distance.
-- m and ef_construction can be tuned; defaults shown are reasonable starting points.
CREATE INDEX IF NOT EXISTS docs_fact_q_embedding_idx
    ON docs USING hnsw (fact_q_embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

CREATE INDEX IF NOT EXISTS docs_procedure_q_embedding_idx
    ON docs USING hnsw (procedure_q_embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

CREATE INDEX IF NOT EXISTS docs_constraint_q_embedding_idx
    ON docs USING hnsw (constraint_q_embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

-- GIN index for full-text-style metadata filtering (optional, used by targeted queries).
CREATE INDEX IF NOT EXISTS docs_metadata_idx ON docs USING gin (metadata);
