#!/usr/bin/env python3
"""
Create an Excel report and upload it to an FTP server.

The remote path is: /<year>/<month>/<auto-generated-filename>
Folders are created if they don't exist.

Run from project root:
    python scripts/send_report_ftp.py --from 2024-01-01 --to 2024-01-31 --creds ftp.conf

Credentials file format (plain text, one key=value per line):
    ip=192.168.1.1
    port=21
    username=user
    password=secret
"""

from __future__ import annotations

import argparse
import asyncio
import ftplib
import logging
import sys
import tempfile
from datetime import datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from audit.excel_formatter import ExcelFormatter  # noqa: E402

# ── Args ──────────────────────────────────────────────────────────────────────
_parser = argparse.ArgumentParser(description="Create Excel report and upload to FTP")
_parser.add_argument("--from", dest="date_from", required=True, metavar="YYYY-MM-DD", help="Start date (inclusive)")
_parser.add_argument("--to",   dest="date_to",   required=True, metavar="YYYY-MM-DD", help="End date (inclusive)")
_parser.add_argument("--creds", required=True, metavar="FILE", help="Credentials file (ip=, port=, username=, password=)")
_args = _parser.parse_args()


def _parse_date(value: str, label: str) -> datetime:
    try:
        return datetime.strptime(value, "%Y-%m-%d").replace(tzinfo=timezone.utc)
    except ValueError:
        _parser.error(f"--{label}: expected YYYY-MM-DD, got {value!r}")


def _load_creds(path: str) -> dict[str, str]:
    creds: dict[str, str] = {}
    required = {"ip", "port", "username", "password"}
    try:
        for line in Path(path).read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            key, _, value = line.partition("=")
            creds[key.strip()] = value.strip()
    except FileNotFoundError:
        _parser.error(f"--creds: file not found: {path!r}")
    missing = required - creds.keys()
    if missing:
        _parser.error(f"--creds: missing keys: {', '.join(sorted(missing))}")
    return creds


date_from = _parse_date(_args.date_from, "from")
date_to   = _parse_date(_args.date_to,   "to") + timedelta(days=1)
creds     = _load_creds(_args.creds)

_auto_name = f"report_{_args.date_from}_to_{_args.date_to}.xlsx"

# ── Logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
log = logging.getLogger(__name__)


def _ftp_makedirs(ftp: ftplib.FTP, path: str) -> None:
    """Create remote directory tree, skipping parts that already exist."""
    parts = [p for p in path.split("/") if p]
    current = ""
    for part in parts:
        current += f"/{part}"
        try:
            ftp.mkd(current)
        except ftplib.error_perm as e:
            if "550" not in str(e):
                raise


def _upload(local_path: Path, remote_filename: str) -> None:
    now = datetime.now()
    remote_dir = f"/{now.year}/{now.month:02d}"
    remote_path = f"{remote_dir}/{remote_filename}"

    log.info("Connecting to FTP %s:%s", creds["ip"], creds["port"])
    with ftplib.FTP() as ftp:
        ftp.connect(host=creds["ip"], port=int(creds["port"]))
        ftp.login(user=creds["username"], passwd=creds["password"])
        ftp.set_pasv(True)

        _ftp_makedirs(ftp, remote_dir)
        ftp.cwd(remote_dir)

        with local_path.open("rb") as f:
            ftp.storbinary(f"STOR {remote_filename}", f)

    log.info("Uploaded → ftp://%s%s", creds["ip"], remote_path)


async def main() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        local_path = Path(tmp) / _auto_name
        log.info("Creating report for %s — %s", _args.date_from, _args.date_to)
        async with ExcelFormatter(local_path) as fmt:
            written = await fmt.export_period(date_from, date_to)

        if not written:
            log.info("No records found for the given period — nothing uploaded.")
            return

        log.info("Wrote %d row(s), uploading to FTP…", written)
        _upload(local_path, _auto_name)


if __name__ == "__main__":
    asyncio.run(main())
