#!/usr/bin/env python3
"""
Create an Excel report and upload it to an FTP server.

The remote path is: /<year>/<month>/<auto-generated-filename>
Folders are created if they don't exist.

Run from project root:
    python scripts/send_report_ftp.py --from 2024-01-01 --to 2024-01-31 --creds ftp.conf

Credentials file format (plain text, one key=value per line):
    ip=192.168.1.1
    port=21
    username=user
    password=secret
"""

from __future__ import annotations

import argparse
import asyncio
import logging
import sys
import tempfile
from datetime import datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from audit.excel_formatter import ExcelFormatter  # noqa: E402
from integrations.ftp import load_creds, upload   # noqa: E402

# ── Args ──────────────────────────────────────────────────────────────────────
_parser = argparse.ArgumentParser(description="Create Excel report and upload to FTP")
_parser.add_argument("--from", dest="date_from", required=True, metavar="YYYY-MM-DD", help="Start date (inclusive)")
_parser.add_argument("--to",   dest="date_to",   required=True, metavar="YYYY-MM-DD", help="End date (inclusive)")
_parser.add_argument("--creds", required=True, metavar="FILE", help="Credentials file (ip=, port=, username=, password=)")
_args = _parser.parse_args()


def _parse_date(value: str, label: str) -> datetime:
    try:
        return datetime.strptime(value, "%Y-%m-%d").replace(tzinfo=timezone.utc)
    except ValueError:
        _parser.error(f"--{label}: expected YYYY-MM-DD, got {value!r}")


try:
    creds = load_creds(_args.creds)
except (FileNotFoundError, ValueError) as e:
    _parser.error(f"--creds: {e}")

date_from  = _parse_date(_args.date_from, "from")
date_to    = _parse_date(_args.date_to,   "to") + timedelta(days=1)
_auto_name = f"report_{_args.date_from}_to_{_args.date_to}.xlsx"

# ── Logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
log = logging.getLogger(__name__)


async def main() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        local_path = Path(tmp) / _auto_name
        log.info("Creating report for %s — %s", _args.date_from, _args.date_to)
        async with ExcelFormatter(local_path) as fmt:
            written = await fmt.export_period(date_from, date_to)

        if not written:
            log.info("No records found for the given period — nothing uploaded.")
            return

        log.info("Wrote %d row(s), uploading to FTP…", written)
        upload(local_path, _auto_name, creds)


if __name__ == "__main__":
    asyncio.run(main())
