#!/usr/bin/env python3
"""
Create an Excel report and upload it to an FTP server.

The remote path is: /<year>/<month>/<auto-generated-filename>
Folders are created if they don't exist.

Run from project root:
    python scripts/operator/send_report_ftp.py --from 2024-01-01 --to 2024-01-31 --org MDS --creds ftp.conf

Credentials file format (plain text, one key=value per line):
    ip=192.168.1.1
    port=21
    username=user
    password=secret
"""

from __future__ import annotations

import argparse
import asyncio
import logging
import sys
import tempfile
from datetime import datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT / "src"))

from audit.excel_formatter import ExcelFormatter  # noqa: E402
from integrations.ftp import load_creds, upload   # noqa: E402
from parsers.inspection_order import (  # noqa: E402
    load_inspection_format,
    load_inspection_formats,
)
from storage.organizations_storage import OrganizationsStorage  # noqa: E402

# ── Args ──────────────────────────────────────────────────────────────────────
_parser = argparse.ArgumentParser(description="Create Excel report and upload to FTP")
_parser.add_argument("--from", dest="date_from", required=True, metavar="YYYY-MM-DD", help="Start date (inclusive)")
_parser.add_argument("--to",   dest="date_to",   required=True, metavar="YYYY-MM-DD", help="End date (inclusive)")
_parser.add_argument("--org", required=True, choices=("Alenka", "MDS"), help="Organization to export (required: a report is always scoped to one org)")
_parser.add_argument("--creds", required=True, metavar="FILE", help="Credentials file (ip=, port=, username=, password=)")
_parser.add_argument(
    "--format",
    default=None,
    metavar="NAME",
    help="Reorder ДанныеОсмотра fields using resources/inspection_formats.json "
         "[<org>][<NAME>], and draw the fields a recognised template is missing "
         "as «не заполнено». Omit to leave the record as 1C sent it.",
)
_args = _parser.parse_args()

INSPECTION_ORDER = (
    load_inspection_format(_args.org, _args.format) if _args.format else None
)
# Шаблоны той же клиники: по ним запись опознаётся и дорисовывается.
INSPECTION_FORMATS = load_inspection_formats(_args.org) if _args.format else None


def _parse_date(value: str, label: str) -> datetime:
    try:
        return datetime.strptime(value, "%Y-%m-%d").replace(tzinfo=timezone.utc)
    except ValueError:
        _parser.error(f"--{label}: expected YYYY-MM-DD, got {value!r}")


try:
    creds = load_creds(_args.creds)
except (FileNotFoundError, ValueError) as e:
    _parser.error(f"--creds: {e}")

date_from  = _parse_date(_args.date_from, "from")
date_to    = _parse_date(_args.date_to,   "to") + timedelta(days=1)
_auto_name = f"report_{_args.org}_{_args.date_from}_to_{_args.date_to}.xlsx"

# ── Logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
log = logging.getLogger(__name__)


async def main() -> None:
    async with OrganizationsStorage() as organizations:
        org_id = await organizations.get_id_by_name(_args.org)

    with tempfile.TemporaryDirectory() as tmp:
        local_path = Path(tmp) / _auto_name
        log.info("Creating report for %s — %s (org=%s)", _args.date_from, _args.date_to, _args.org)
        async with ExcelFormatter(
            local_path, org_name=_args.org,
            order_tokens=INSPECTION_ORDER, formats=INSPECTION_FORMATS,
        ) as fmt:
            written = await fmt.export_period(date_from, date_to, org_id)

        if not written:
            log.info("No records found for the given period — nothing uploaded.")
            return

        log.info("Wrote %d row(s), uploading to FTP…", written)
        upload(local_path, _auto_name, creds)


if __name__ == "__main__":
    asyncio.run(main())
